services:
  - type: web
    name: jarvisos-video-meet
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
